### ISSUE TITLE
fNIRS Explorer

### ISSUE THREAD

**Issue by gkatsara** [biosignalsplux/c-sharp-sample#1]
Is fNIRS Explorer supported by this API ?

**Comment by diogotecelao** [comment]
@gkatsara yes, the C# API does support the fNIRS Explorer. Do you have any particular question on the implementation?

**Comment by gkatsara** [comment]
@diogotecelao 
When I run the code, I see the following on the console but my fNIRS device never starts recording.

![Χωρίς τίτλο](https://user-images.githubusercontent.com/73194495/102820989-e1801380-43de-11eb-8118-a1a7a25ae689.png)

I think there is a problem with my device description. Could you please help me solve this problem?

**Comment by diogotecelao** [comment]
@gkatsara I assume that you are using the sample code provided with the API?

**Comment by gkatsara** [comment]
@diogotecelao  yes , of course

**Comment by diogotecelao** [comment]
@gkatsara We've just added a sample app adjusted to work with the fNIRS Explorer. Please also note that we've added a new version of the 64-bits API, as the setParameters functionality (needed for your use-case) was disabled in this API. Hope this helps you.

**Comment by gkatsara** [comment]
@diogotecelao  Thank you very much for your reply. It seems to work fine. I would like to ask you what exactly does each column in the console show me? Do I see this series of data [""R1"", ""IR1"", ""R2"", ""IR2"", ""ACC1"", ""ACC2"", ""ACC3""] or do they have a different order?

**Comment by diogotecelao** [comment]
@gkatsara, the order in which the data appears depends on the order in which you set the sources. In this case, you first set the accelerometer sources and then the SpO2:
`List<PluxDotNet.Source> srcs = new List<PluxDotNet.Source>() { src_acc, src_spo2 };`

Hence, the data output order is the following: accX, accY, accZ, Red1, IRed1, Red2, IRed2

**Comment by gkatsara** [comment]
Ok @diogotecelao, thank you very much. I really appreciate your help!
